export const GET_TOP_HEADLINES_REQUEST         = 'GET_TOP_HEADLINES_REQUEST';
export const GET_TOP_HEADLINES_SUCCESS         = 'GET_TOP_HEADLINES_SUCCESS';
export const GET_TOP_HEADLINES_FAILURE         = 'GET_TOP_HEADLINES_FAILURE';
export type GET_TOP_HEADLINES_REQUEST          = typeof GET_TOP_HEADLINES_REQUEST;
export type GET_TOP_HEADLINES_SUCCESS          = typeof GET_TOP_HEADLINES_SUCCESS;
export type GET_TOP_HEADLINES_FAILURE          = typeof GET_TOP_HEADLINES_FAILURE;